### ISSUE TITLE
`ipconfig` command error. (Linux)

### ISSUE THREAD

**Issue by KookaburraShell** [AZProductions/Kookaburra#100]
## Bug Report

**Current Behavior**
`ipconfig` command.

**Logs**
```
lo
  DNS suffix .............................. : (router name)
  DNS enabled ............................. : True
Unhandled exception. System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties.get_IsDynamicDnsEnabled()
   at KookaburraShell.Program.Main(String[] args)
Aborted (core dumped)
```

**Environment**
- Kookaburra version(s): <= 0.8.1 beta-1
- OS: Linux Mint
- How you are using Kookaburra: `cli`

**Comment by AZProductions** [comment]
Removed command in Linux version of Kookaburra.
